# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import my_remote_procedure_call_pb2 as my__remote__procedure__call__pb2


class DiferentOperationsHandlerStub(object):
  """The service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.takeIntNumber_ReturnIntNumber = channel.unary_unary(
        '/my_remote_procedure_call.DiferentOperationsHandler/takeIntNumber_ReturnIntNumber',
        request_serializer=my__remote__procedure__call__pb2.IntNumberMessage.SerializeToString,
        response_deserializer=my__remote__procedure__call__pb2.IntNumberMessage.FromString,
        )
    self.takeIntNumbers_ReturnIntNumber = channel.unary_unary(
        '/my_remote_procedure_call.DiferentOperationsHandler/takeIntNumbers_ReturnIntNumber',
        request_serializer=my__remote__procedure__call__pb2.TenIntNumbersMessage.SerializeToString,
        response_deserializer=my__remote__procedure__call__pb2.IntNumberMessage.FromString,
        )
    self.takeIntNumber_ReturnIntNumbers = channel.unary_unary(
        '/my_remote_procedure_call.DiferentOperationsHandler/takeIntNumber_ReturnIntNumbers',
        request_serializer=my__remote__procedure__call__pb2.IntNumberMessage.SerializeToString,
        response_deserializer=my__remote__procedure__call__pb2.TenIntNumbersMessage.FromString,
        )
    self.takeLongIntNumber_ReturnLongIntNumbers = channel.unary_unary(
        '/my_remote_procedure_call.DiferentOperationsHandler/takeLongIntNumber_ReturnLongIntNumbers',
        request_serializer=my__remote__procedure__call__pb2.LongIntNumberMessage.SerializeToString,
        response_deserializer=my__remote__procedure__call__pb2.LongIntNumberMessage.FromString,
        )
    self.takeFloatNumber_ReturnFloatNumber = channel.unary_unary(
        '/my_remote_procedure_call.DiferentOperationsHandler/takeFloatNumber_ReturnFloatNumber',
        request_serializer=my__remote__procedure__call__pb2.FloatNumberMessage.SerializeToString,
        response_deserializer=my__remote__procedure__call__pb2.FloatNumberMessage.FromString,
        )
    self.takeString_ReturnString = channel.unary_unary(
        '/my_remote_procedure_call.DiferentOperationsHandler/takeString_ReturnString',
        request_serializer=my__remote__procedure__call__pb2.StringMessage.SerializeToString,
        response_deserializer=my__remote__procedure__call__pb2.StringMessage.FromString,
        )
    self.takeObject_ReturnObject = channel.unary_unary(
        '/my_remote_procedure_call.DiferentOperationsHandler/takeObject_ReturnObject',
        request_serializer=my__remote__procedure__call__pb2.ObjectMessage.SerializeToString,
        response_deserializer=my__remote__procedure__call__pb2.ObjectMessage.FromString,
        )


class DiferentOperationsHandlerServicer(object):
  """The service definition.
  """

  def takeIntNumber_ReturnIntNumber(self, request, context):
    """Receives an int number and returns an int number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def takeIntNumbers_ReturnIntNumber(self, request, context):
    """Receives 10 int numbers and returns an int number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def takeIntNumber_ReturnIntNumbers(self, request, context):
    """Receives an int number and returns 10 int number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def takeLongIntNumber_ReturnLongIntNumbers(self, request, context):
    """Receives a long int number and returns a long int number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def takeFloatNumber_ReturnFloatNumber(self, request, context):
    """Receives a float numbers and returns a float number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def takeString_ReturnString(self, request, context):
    """Receives a string and returns a string
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def takeObject_ReturnObject(self, request, context):
    """Receives an object and returns an object
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiferentOperationsHandlerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'takeIntNumber_ReturnIntNumber': grpc.unary_unary_rpc_method_handler(
          servicer.takeIntNumber_ReturnIntNumber,
          request_deserializer=my__remote__procedure__call__pb2.IntNumberMessage.FromString,
          response_serializer=my__remote__procedure__call__pb2.IntNumberMessage.SerializeToString,
      ),
      'takeIntNumbers_ReturnIntNumber': grpc.unary_unary_rpc_method_handler(
          servicer.takeIntNumbers_ReturnIntNumber,
          request_deserializer=my__remote__procedure__call__pb2.TenIntNumbersMessage.FromString,
          response_serializer=my__remote__procedure__call__pb2.IntNumberMessage.SerializeToString,
      ),
      'takeIntNumber_ReturnIntNumbers': grpc.unary_unary_rpc_method_handler(
          servicer.takeIntNumber_ReturnIntNumbers,
          request_deserializer=my__remote__procedure__call__pb2.IntNumberMessage.FromString,
          response_serializer=my__remote__procedure__call__pb2.TenIntNumbersMessage.SerializeToString,
      ),
      'takeLongIntNumber_ReturnLongIntNumbers': grpc.unary_unary_rpc_method_handler(
          servicer.takeLongIntNumber_ReturnLongIntNumbers,
          request_deserializer=my__remote__procedure__call__pb2.LongIntNumberMessage.FromString,
          response_serializer=my__remote__procedure__call__pb2.LongIntNumberMessage.SerializeToString,
      ),
      'takeFloatNumber_ReturnFloatNumber': grpc.unary_unary_rpc_method_handler(
          servicer.takeFloatNumber_ReturnFloatNumber,
          request_deserializer=my__remote__procedure__call__pb2.FloatNumberMessage.FromString,
          response_serializer=my__remote__procedure__call__pb2.FloatNumberMessage.SerializeToString,
      ),
      'takeString_ReturnString': grpc.unary_unary_rpc_method_handler(
          servicer.takeString_ReturnString,
          request_deserializer=my__remote__procedure__call__pb2.StringMessage.FromString,
          response_serializer=my__remote__procedure__call__pb2.StringMessage.SerializeToString,
      ),
      'takeObject_ReturnObject': grpc.unary_unary_rpc_method_handler(
          servicer.takeObject_ReturnObject,
          request_deserializer=my__remote__procedure__call__pb2.ObjectMessage.FromString,
          response_serializer=my__remote__procedure__call__pb2.ObjectMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'my_remote_procedure_call.DiferentOperationsHandler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
